export const APPOINTMENT_FEE = Number(process.env.APPOINTMENT_FEE ?? 20.00);
export const APPOINTMENT_FEE_NPR = APPOINTMENT_FEE*120
export const MAX_USER_DAILY_APPOINTMENTS = Number(process.env.MAX_USER_DAILY_APPOINTMENTS) || 3;
export const MAX_DOCTOR_DAILY_APPOINTMENTS = Number(process.env.MAX_DOCTOR_DAILY_APPOINTMENTS) || 30;